### ISSUE TITLE
VLC: available variables doesn't work

### ISSUE THREAD

**Issue by randomizeguy** [bitfocus/companion-module-videolan-vlc#20] opened 2020-12-11 14:52 UTC
Hey,

the available variables which shown in the help for videolan vlc doesn't work in my 2.1.2 (f4bcaf3-2679) companion with the latest vlc. The names of the items does not shown up even the remaining time of the playing item. I just got "Play $NA" and "00:00:00" on my Stream Deck and companion no matter which id oder item I choose or is active. The $(vlc:r_stat) is the only variable which works without any issue in my companion. I've tried the other one in totally empty buttons and in combination with Play without any success.

**Comment by istnv** [comment] 2020-12-15 23:12
How many items in the playlist? Your description would be the result of an empty list.

**Comment by randomizeguy** [comment] 2020-12-17 06:46
I've tried it with a various number of 1-4 items.

**Comment by istnv** [comment] 2020-12-17 06:49
Which version VLC?

**Comment by randomizeguy** [comment] 2020-12-17 07:10
V.3.0.11.

**Comment by istnv** [comment] 2020-12-17 07:21
Some of the variables do not have a value if a clip is not playing.

**Comment by choeke** [comment] 2020-12-18 09:18
Hello! Is there any solution to this problem yet? I am running on Companion 2.1.2. I tested VLC Versions 3.08 and 3.11. Nothing did the job. Controls work like a charm, dynamic variables doesn't.  I am specifically in need for the time remaining. Are there any settings in VLC you need to adjust to make it work? Thanks in advance!

**Comment by istnv** [comment] 2020-12-18 09:40
How are you entering the dynamic variables? I cannot reproduce the problem so I cannot fix your issue.

**Comment by choeke** [comment] 2020-12-18 09:43
I simply copy and paste them from the list of variables.

$(VLC:r_ss)

VLC is my custom-instance name. 
I must admit that I am new to companion

**Comment by istnv** [comment] 2020-12-18 09:45
The variables are case sensitive. Make sure the instance name matches what is listed under 'Label'

**Comment by McHauge** [comment] 2020-12-18 09:51
@choeke Quick question, would it be possible for you to take a screenshot of you VLC instance in companion, and the button where you're trying to use it

pigture below as an exsample: (by the way, i don't have VLC running or installed, just a raw module)
![image](https://user-images.githubusercontent.com/31018035/102600283-ee6edf80-411e-11eb-9bb9-c75f4aef0575.png)

**Comment by choeke** [comment] 2020-12-18 09:55
I recently changed the labels name to make sure there is no conflict by naming it vlc. Result stays the same. The button itself should do nothing than displaying the remaining time. 

<img width="849" alt="Bildschirmfoto 2020-12-18 um 10 52 12" src="https://user-images.githubusercontent.com/76129313/102600583-4d345900-411f-11eb-921a-49a9ea961063.png">
<img width="848" alt="Bildschirmfoto 2020-12-18 um 10 53 04" src="https://user-images.githubusercontent.com/76129313/102600607-54f3fd80-411f-11eb-9e4f-8a38f2737410.png">

**Comment by choeke** [comment] 2020-12-18 09:55
The button displays "00" permanently.

**Comment by istnv** [comment] 2020-12-18 09:58
What does that first screenshot look like when something is playing?

**Comment by choeke** [comment] 2020-12-18 10:03
Stays nearly the same. Just the "playing Status" changes. 
I just took a look in the log. Is it connected to the following error: "18. 10:47:09 instance(Videoeinspieler): connect ECONNREFUSED 127.0.0.1:8080"
Despite that: Status says "OK" and all the buttons are working

**Comment by istnv** [comment] 2020-12-18 10:07
ECONNREFUSED will show if VLC is not running when companion starts. 
Did the log show 'Connected to..' after that?

**Comment by istnv** [comment] 2020-12-18 10:08
Can you post a screen shot of your VLC playlist?

**Comment by choeke** [comment] 2020-12-18 10:13
The log didn't show "connected to.." afterwards. But by closing companion and restarting it while vlc is running, the error doesn't appear. 
<img width="1327" alt="Bildschirmfoto 2020-12-18 um 11 11 59" src="https://user-images.githubusercontent.com/76129313/102602575-04ca6a80-4122-11eb-951c-85280b2604d6.png">

**Comment by istnv** [comment] 2020-12-18 10:25
Do you have the log filtered? The error will always show up but the connect needs the Info filter enabled:
![companion-log](https://user-images.githubusercontent.com/51003420/102603758-16872000-40d8-11eb-912a-4335605efebd.png)
I need to unpack my Macbook to see if it is something Mac specific you are experiencing.

**Comment by choeke** [comment] 2020-12-18 10:28
Shame on me. I didn't have the info-filter enabled. Yes, it does show "connected to.."

**Comment by istnv** [comment] 2020-12-18 10:36
Does turning off 'Increase timer resolution' make a difference?

**Comment by choeke** [comment] 2020-12-18 10:39
No change. 
For the record: I really appreciate your help.

**Comment by istnv** [comment] 2020-12-18 10:44
I need to log out for now. I will load up the mac later today to see what I can discover.

**Comment by choeke** [comment] 2020-12-18 10:45
Thank you very much.

**Comment by istnv** [comment] 2020-12-18 21:32
For some reason, VLC localization also applies to the API. 
The module looks for data from VLC labeled "Playlist" to fill in the playlist items. When VLC operates in German, it returns the data as "Wiedergabeliste" which gets skipped.
It is probably the same for other languages. Usually an API does not alter by locale so information defined as "Playlist" should always match internally.
There will be a change submitted to look at data by position instead of label so the module will still work.

Workaround for now: change the VLC language preference from 'Auto' to 'English' (either one).

**Comment by choeke** [comment] 2020-12-18 21:40
Great! Thank you very much. I am absolutely happy about the workaround. What a support 👍

**Comment by Naesstrom** [comment] 2021-01-20 07:59
> For some reason, VLC localization also applies to the API.
> The module looks for data from VLC labeled "Playlist" to fill in the playlist items. When VLC operates in German, it returns the data as "Wiedergabeliste" which gets skipped.
> It is probably the same for other languages. Usually an API does not alter by locale so information defined as "Playlist" should always match internally.
> There will be a change submitted to look at data by position instead of label so the module will still work.
> 
> Workaround for now: change the VLC language preference from 'Auto' to 'English' (either one).

Thanks a million for this, had problem the buttons didn't work at all until I changed the language from Swedish to English!

**Comment by ywiskerke** [comment] 2023-01-14 23:36
I'm running 2.4.1 (2.4.1+4900-75af9576)](https://bitfocus.io/companion/) and VLC 3.0.18 and I still have this issue. Language is set to English. Companion does not show the variables... counters all 0, none of the variables work. The control command do!

Any idea where to look? Mind you the screenshot below was made when VLC was playing Video
![Screenshot 2023-01-15 at 00 35 28](https://user-images.githubusercontent.com/13993949/212501706-ad148f52-6374-45a1-b653-ff04783aac99.png)

**Comment by istnv** [comment] 2023-01-14 23:50
@ywiskerke 
The space ' ' in the connection label is probably causing your issue.

**Comment by ywiskerke** [comment] 2023-01-15 09:21
@istnv Huh? It had been working for literally three years. And I can confirm that is NOT the problem. Changed the connection name to vlc_mm2 and the variables still don't work.

Also I have several Connections in Companion Labels with spaces in them. Never had of have problems with it.

I double checked the VLC instance with `curl -u :<password> http://<vlc_host>:<vlc_port>/requests/status.json` and it returned all the variables.
```
{
  "fullscreen":0,
  "stats":{
    "inputbitrate":0.030147813260555,
    "sentbytes":0,
    "lostabuffers":0,
    "averagedemuxbitrate":0,
    "readpackets":24524,
    "demuxreadpackets":0,
    "lostpictures":0,
    "displayedpictures":0,
    "sentpackets":0,
    "demuxreadbytes":30564504,
    "demuxbitrate":0.029998248443007,
    "playedabuffers":44654,
    "demuxdiscontinuity":0,
    "decodedaudio":89309,
    "sendbitrate":0,
    "readbytes":30568058,
    "averageinputbitrate":0,
    "demuxcorrupted":0,
    "decodedvideo":0
  },
  "audiodelay":0,
  "apiversion":3,
  "currentplid":283,
  "time":4194,
  "volume":218,
  "length":4361,
  "random":false,
  "audiofilters":{
    "filter_0":""
  },
  "rate":1,
  "videoeffects":{
    "hue":0,
    "saturation":1,
    "contrast":1,
    "brightness":1,
    "gamma":1
  },
  "state":"playing",
  "loop":false,
  "version":"3.0.18 Vetinari",
  "position":0.96229135990143,
  "information":{
    "chapter":0,
    "chapters":[],
    "title":0,
    "category":{
      "meta":{
        "filename":"Chopin Spring Waltz 1 hours.mp3",
        "title":"Chopin Spring Waltz 1 hours"
      },
      "Stream 0":{
        "Bitrate":"32 kb/s",
        "Codec":"MPEG Audio layer 1/2 (mpga)",
        "Channels":"Stereo",
        "Bits_per_sample":"32",
        "Type":"Audio",
        "Sample_rate":"48000 Hz"
      }
    },
    "titles":[]
  },
  "repeat":false,
  "subtitledelay":0,
  "equalizer":[]
}
```

**Comment by istnv** [comment] 2023-01-15 20:28
> @istnv Huh? It had been working for literally three years. And I can confirm that is NOT the problem. Changed the connection name to vlc_mm2 and the variables still don't work.
> 
Did you change the variable reference in the button text to match?
Unfortunately, those do not change automatically.

You may have noticed the many improvements to companion lately such as Custom variables and Triggers. Companion should now prevent you from using spaces in the connection name.

In order to take advantage of these new features, certain restrictions were required for the variable and connection names. 
Last October, VLC was updated to be able to use custom variables in the button actions.
Yours is the first mention of the issue since then.

**Comment by ywiskerke** [comment] 2023-01-16 10:25
Ah, I did change the label and the actions do change the name automatically, so I assumed the variables would too. Feature request?

I'll check my setup to see how it works tomorrow. I have a streaming gig tomorrow.

I'm running this off a NUC with Linux in my production setup. Ever since I needed Custom variables and Triggers, I started running the latest directly of Github, now 2.4.1. I run a very extensive test script to see if everything still works before a job. So far it's been awesome.

**Comment by istnv** [comment] 2023-01-16 15:43
> Ah, I did change the label and the actions do change the name automatically, so I assumed the variables would too. Feature request?
> 
Good idea. The price of progress, sometimes :)

> I'll check my setup to see how it works tomorrow. I have a streaming gig tomorrow.
> 
> I'm running this off a NUC with Linux in my production setup. Ever since I needed Custom variables and Triggers, I started running the latest directly of Github, now 2.4.1. I run a very extensive test script to see if everything still works before a job. So far it's been awesome.

I develop on Linux myself. Since the Raspberry Pi supply shrank, the small Intel NUCs have been a great substitute. I usually install Lubuntu, Companion, and a shared file storage drive for other show files and notes.

**Comment by ywiskerke** [comment] 2023-01-16 17:40
@istnv I can confirm is still NOT working.

I even reproduced it running it of a RPI with git clone of the latest repo [2.4.1 (2.4.1+4900-75af9576)]. In this version the labels for variables ARE changed automatically btw. The version of VLC is 3.0.18 and the API commands just work, so it must be in the variable collection. The curl call to the HTTP endpoint works. See below.
However, checking connections and then clicking on the $ next to the listing of the connections reveals no variables are collected.
![image](https://user-images.githubusercontent.com/13993949/212738263-e8954679-5d6b-47fc-9fc6-ada1f3d304c8.png)

And VLC is currently playing... 
```
...
},
  "state":"playing",
  "loop":false,
  "version":"3.0.18 Vetinari",
  "position":0.015286860987544,
  "information":{
    "chapter":0,
    "chapters":[],
    "title":0,
    "category":{
      "meta":{
        "encoded_by":"Lavf58.45.100",
        "filename":"Teddy Swims - Let Me Love You (Mario Cover)-khdH-heeojU.m4a"
      },
...
```

**Comment by ywiskerke** [comment] 2023-01-16 18:11
Tell me how to help to debug this...

**Comment by ywiskerke** [comment] 2023-01-16 18:39
I managed to find what the problem is. The difference is in the playlist vs media library. I ran audio from my media library and then Companion is unable to grab the variables. When I open a 'normal' playlist the problem is gone.
I can't seem to find the difference between the /requests/status.json output between both situations. Still interesting find.

**Comment by istnv** [comment] 2023-01-16 18:40
@ywiskerke What version of the VLC connection? Look in the companion log. 
It looks like the module was reformatted to work with 3.0. I have not tested the latest version.
I will need to reload my copy from github to test.

**Comment by ywiskerke** [comment] 2023-01-16 18:43
I managed to narrow it down to the following condition. If the normal playlist is empty and you select a file from the media library variables will be empty. When there are items in the playlist, even though you're not playing them, select an item from the media library to play and then the variables are populated.

Are you checking if the playlist is empty somewhere by any chance?

**Comment by istnv** [comment] 2023-01-16 18:48
> Are you checking if the playlist is empty somewhere by any chance?

There is no way to subscribe to status from VLC so the module is constantly polling/asking for information. It does stop polling when the playlist is empty.

**Comment by ywiskerke** [comment] 2023-01-16 18:53
There you go. I mostly run from media library since easier to kick off certain list items.
Couldn't you check for _state: playing_?

**Comment by ywiskerke** [comment] 2023-01-16 18:57
So it's in the following line in [index.js:299](https://github.com/bitfocus/companion-module-videolan-vlc/blob/23f97a9c06929cb5b977ed172a8b4258344fab78/index.js#L299)
`		} else if (this.PlayIDs.length > 0) {`

This causes my condition with an empty playlist and about 300 files in my media library. ;)

In addition if the playlist has one item in it, the time variables work, but the item name is not displayed, even though the /request/status.json show what item name is played.

It seems like tying everything to the playlist is not the right thing to do in this case.

**Comment by istnv** [comment] 2023-01-16 19:23
It is an attempt to reduce network traffic when not playing.
I would guess the majority of uses are playlists, not media libraries.

That test could be `(this.pbInfo.state != 'stopped')` 
I am not able to update this for a couple of days.

**Comment by ywiskerke** [comment] 2023-01-16 19:28
No worries, I know the work-around for now. Create a long playlist. Thank you for bearing with me on this.
I forgot how much I love to debug and code... maybe I'll start contributing myself.

**Closed as completed** 2023-04-06 20:13 UTC
